name: android_engine_test
publish_to: 'none'

environment:
  sdk: '>=3.5.0-219.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

dev_dependencies:
  path: ^1.9.0
  test: 1.25.6
